# Generated by Django 4.2.23 on 2025-08-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
