# Generated by Django 4.2.23 on 2025-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findus', '0002_remove_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsmanprofile',
            name='service_category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('carpentry', 'Carpentry'), ('painting', 'Painting'), ('masonry', 'Masonry'), ('roofing', 'Roofing'), ('landscaping', 'Landscaping'), ('appliance', 'Appliance Repair'), ('hvac', 'HVAC Services'), ('other', 'Other')], max_length=100),
        ),
    ]
