# Generated by Django 4.2.23 on 2025-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findus', '0009_alter_craftsmanprofile_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumber'), ('electrical', 'Electrician'), ('ac_technician', 'AC Technician'), ('carpentry', 'Carpenter'), ('tiling', 'Tiler'), ('painting', 'Painter'), ('furniture_maker', 'Furniture Maker'), ('fumigation', 'Fumigator'), ('dstv_technician', 'DSTV Technician'), ('gas_appliance', 'Gas Appliance Technician'), ('pop_worker', 'POP Worker'), ('cleaning', 'Cleaner'), ('aluminium_worker', 'Aluminium Worker'), ('welding', 'Welder'), ('roofing', 'Roof Technician'), ('solar_power', 'Solar Power Technician'), ('masonry', 'Mason'), ('glass_partitioning', 'Glass/Partitioning Worker'), ('bricklayer', 'Bricklayer / Plasterer'), ('foreman', 'Foreman'), ('landscaping', 'Landscaping'), ('appliance_repair', 'Appliance Repair'), ('hvac', 'HVAC Services'), ('security_installation', 'CCTV / Security System Technician'), ('generator_technician', 'Generator Technician'), ('interior_design', 'Interior Designer'), ('flooring', 'Flooring / Epoxy Work'), ('metal_fabrication', 'Metal Fabrication'), ('waterproofing', 'Waterproofing Specialist'), ('pest_control', 'Pest Control'), ('scaffolding', 'Scaffolding Worker'), ('site_supervisor', 'Site Supervisor'), ('other', 'Other')], max_length=50),
        ),
    ]
