# Generated by Django 4.2.27 on 2026-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0012_savedservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("plumbing", "Plumber"),
                            ("electrical", "Electrician"),
                            ("ac_technician", "AC Technician"),
                            ("carpentry", "Carpenter"),
                            ("tiling", "Tiler"),
                            ("painting", "Painter"),
                            ("furniture_maker", "Furniture Maker"),
                            ("fumigation", "Fumigator"),
                            ("dstv_technician", "DSTV Technician"),
                            ("gas_appliance", "Gas Appliance Technician"),
                            ("pop_worker", "POP Worker"),
                            ("cleaning", "Cleaner"),
                            ("aluminium_worker", "Aluminium Worker"),
                            ("welding", "Welder"),
                            ("roofing", "Roof Technician"),
                            ("solar_power", "Solar Power Technician"),
                            ("masonry", "Mason"),
                            ("glass_partitioning", "Glass/Partitioning Worker"),
                            ("bricklayer", "Bricklayer / Plasterer"),
                            ("foreman", "Foreman"),
                            ("landscaping", "Landscaping"),
                            ("appliance_repair", "Appliance Repair"),
                            ("hvac", "HVAC Services"),
                            (
                                "security_installation",
                                "CCTV / Security System Technician",
                            ),
                            ("generator_technician", "Generator Technician"),
                            ("interior_design", "Interior Designer"),
                            ("flooring", "Flooring / Epoxy Work"),
                            ("metal_fabrication", "Metal Fabrication"),
                            ("waterproofing", "Waterproofing Specialist"),
                            ("pest_control", "Pest Control"),
                            ("scaffolding", "Scaffolding Worker"),
                            ("site_supervisor", "Site Supervisor"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("service_needed", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("notify_updates", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
