# Generated by Django 4.2.27 on 2026-01-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0013_waitinglist"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abruzzo", "Abruzzo"),
                    ("aosta_valley", "Aosta Valley (Valle d'Aosta)"),
                    ("apulia", "Apulia (Puglia)"),
                    ("basilicata", "Basilicata"),
                    ("calabria", "Calabria"),
                    ("campania", "Campania"),
                    ("emilia_romagna", "Emilia-Romagna"),
                    ("friuli_venezia_giulia", "Friuli-Venezia Giulia"),
                    ("lazio", "Lazio"),
                    ("liguria", "Liguria"),
                    ("lombardy", "Lombardy (Lombardia)"),
                    ("marche", "Marche"),
                    ("molise", "Molise"),
                    ("piedmont", "Piedmont (Piemonte)"),
                    ("sardinia", "Sardinia (Sardegna)"),
                    ("sicily", "Sicily (Sicilia)"),
                    (
                        "trentino_south_tyrol",
                        "Trentino-South Tyrol (Trentino-Alto Adige)",
                    ),
                    ("tuscany", "Tuscany (Toscana)"),
                    ("umbria", "Umbria"),
                    ("veneto", "Veneto"),
                ],
                help_text="Select the region where you provide this service",
                max_length=30,
                null=True,
            ),
        ),
    ]
