# Generated by Django 4.2.27 on 2026-02-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findus', '0015_boostrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='notify_updates',
        ),
    ]
