# Generated by Django 4.2.27 on 2026-02-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findus', '0017_remove_craftsmanprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='service_category',
        ),
    ]
