# Generated by Django 4.2.28 on 2026-02-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0019_remove_customerprofile_address_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_status", "-created_at"],
                name="findus_serv_service_e4ee79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "service_status"],
                name="findus_serv_categor_bbc70e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["region", "service_status"],
                name="findus_serv_region_7218a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["availability"], name="findus_serv_availab_42f450_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["job_size"], name="findus_serv_job_siz_ad2883_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["price_type"], name="findus_serv_price_t_aa43da_idx"
            ),
        ),
    ]
