# Generated by Django 4.2.28
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0020_service_findus_serv_service_e4ee79_idx_and_more"),
    ]

    operations = [
        # Index for craftsman lookup
        migrations.AddIndex(
            model_name='service',
            index=models.Index(
                fields=['craftsman', 'service_status'], 
                name='svc_craft_stat_idx'
            ),
        ),
        # Index for price filtering (combined)
        migrations.AddIndex(
            model_name='service',
            index=models.Index(
                fields=['hourly_rate'], 
                name='svc_hourly_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(
                fields=['fixed_price'], 
                name='svc_fixed_idx'
            ),
        ),
    ]