# Generated by Django 4.2.28 on 2026-02-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0021_add_additional_service_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="service",
            name="svc_craft_stat_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="svc_hourly_idx",
        ),
        migrations.RemoveIndex(
            model_name="service",
            name="svc_fixed_idx",
        ),
        migrations.AddField(
            model_name="service",
            name="avg_rating",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="service",
            name="review_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
