# Generated by Django 4.2.28 on 2026-02-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0022_remove_service_svc_craft_stat_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="avg_rating",
        ),
        migrations.RemoveField(
            model_name="service",
            name="review_count",
        ),
    ]
