# Generated by Django 4.2.28 on 2026-02-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0023_remove_service_avg_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="avg_rating",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="service",
            name="review_count",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
