# Generated by Django 4.2.28 on 2026-02-14 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0024_service_avg_rating_service_review_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="avg_rating",
        ),
        migrations.RemoveField(
            model_name="service",
            name="review_count",
        ),
    ]
