# Generated by Django 4.2.28 on 2026-02-26 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("findus", "0025_remove_service_avg_rating_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boostrequest",
            options={
                "verbose_name": "boost request",
                "verbose_name_plural": "boost requests",
            },
        ),
        migrations.AlterModelOptions(
            name="craftsmanprofile",
            options={
                "verbose_name": "craftsman profile",
                "verbose_name_plural": "craftsman profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "verbose_name": "customer profile",
                "verbose_name_plural": "customer profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "service", "verbose_name_plural": "services"},
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "user profile",
                "verbose_name_plural": "user profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="waitinglist",
            options={
                "verbose_name": "waiting list entry",
                "verbose_name_plural": "waiting list entries",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=120, null=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="duration_days",
            field=models.IntegerField(verbose_name="duration days"),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="expires_at",
            field=models.DateTimeField(verbose_name="expires at"),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="payment_proof",
            field=models.FileField(
                upload_to="boost_payments/", verbose_name="payment proof"
            ),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boost_requests",
                to="findus.service",
                verbose_name="service",
            ),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="boostrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="business_name",
            field=models.CharField(max_length=255, verbose_name="business name"),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="has_license",
            field=models.BooleanField(default=False, verbose_name="has license"),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="is verified"),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="license_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="license number"
            ),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="phone"),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="craftsman_profiles/",
                verbose_name="profile photo",
            ),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="rating",
            field=models.FloatField(default=0.0, verbose_name="rating"),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="findus.userprofile",
                verbose_name="user profile",
            ),
        ),
        migrations.AlterField(
            model_name="craftsmanprofile",
            name="years_of_experience",
            field=models.CharField(
                choices=[
                    ("0-1", "0-1 years"),
                    ("1-3", "1-3 years"),
                    ("3-5", "3-5 years"),
                    ("5+", "5+ years"),
                ],
                max_length=20,
                verbose_name="years of experience",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="saved_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="saved_by_customers",
                to="findus.service",
                verbose_name="saved services",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="findus.userprofile",
                verbose_name="user profile",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.TextField(verbose_name="comment"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="review",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="findus.customerprofile",
                verbose_name="customer",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="is verified"),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                verbose_name="rating",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="findus.service",
                verbose_name="service",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="service",
            name="availability",
            field=models.CharField(
                choices=[
                    ("immediate", "Immediately Available"),
                    ("24_hours", "Within 24 Hours"),
                    ("48_hours", "Within 48 Hours"),
                    ("scheduled", "By Appointment Only"),
                ],
                default="immediate",
                max_length=20,
                verbose_name="availability",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("plumbing", "Plumber"),
                    ("electrical", "Electrician"),
                    ("ac_technician", "AC Technician"),
                    ("carpentry", "Carpenter"),
                    ("tiling", "Tiler"),
                    ("painting", "Painter"),
                    ("furniture_maker", "Furniture Maker"),
                    ("fumigation", "Fumigator"),
                    ("dstv_technician", "DSTV Technician"),
                    ("gas_appliance", "Gas Appliance Technician"),
                    ("pop_worker", "POP Worker"),
                    ("cleaning", "Cleaner"),
                    ("aluminium_worker", "Aluminium Worker"),
                    ("welding", "Welder"),
                    ("roofing", "Roof Technician"),
                    ("solar_power", "Solar Power Technician"),
                    ("masonry", "Mason"),
                    ("glass_partitioning", "Glass/Partitioning Worker"),
                    ("bricklayer", "Bricklayer / Plasterer"),
                    ("foreman", "Foreman"),
                    ("landscaping", "Landscaping"),
                    ("appliance_repair", "Appliance Repair"),
                    ("hvac", "HVAC Services"),
                    ("security_installation", "CCTV / Security System Technician"),
                    ("generator_technician", "Generator Technician"),
                    ("interior_design", "Interior Designer"),
                    ("flooring", "Flooring / Epoxy Work"),
                    ("metal_fabrication", "Metal Fabrication"),
                    ("waterproofing", "Waterproofing Specialist"),
                    ("pest_control", "Pest Control"),
                    ("scaffolding", "Scaffolding Worker"),
                    ("site_supervisor", "Site Supervisor"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="craftsman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="findus.craftsmanprofile",
                verbose_name="craftsman",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="service",
            name="estimated_duration",
            field=models.CharField(max_length=100, verbose_name="estimated duration"),
        ),
        migrations.AlterField(
            model_name="service",
            name="features",
            field=models.JSONField(blank=True, default=list, verbose_name="features"),
        ),
        migrations.AlterField(
            model_name="service",
            name="fixed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="fixed price",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="hourly rate",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="service_images/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="job_size",
            field=models.CharField(
                choices=[
                    ("small", "Small Job (1-2 hours)"),
                    ("medium", "Medium Job (Half day)"),
                    ("large", "Large Job (Full day+)"),
                    ("project", "Multi-day Project"),
                ],
                default="medium",
                max_length=20,
                verbose_name="job size",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="materials_included",
            field=models.BooleanField(default=False, verbose_name="materials included"),
        ),
        migrations.AlterField(
            model_name="service",
            name="min_hours",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="minimum hours"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="price_type",
            field=models.CharField(
                choices=[("hourly", "Hourly Rate"), ("fixed", "Fixed Price")],
                max_length=10,
                verbose_name="price type",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("abruzzo", "Abruzzo"),
                    ("aosta_valley", "Aosta Valley (Valle d'Aosta)"),
                    ("apulia", "Apulia (Puglia)"),
                    ("basilicata", "Basilicata"),
                    ("calabria", "Calabria"),
                    ("campania", "Campania"),
                    ("emilia_romagna", "Emilia-Romagna"),
                    ("friuli_venezia_giulia", "Friuli-Venezia Giulia"),
                    ("lazio", "Lazio"),
                    ("liguria", "Liguria"),
                    ("lombardy", "Lombardy (Lombardia)"),
                    ("marche", "Marche"),
                    ("molise", "Molise"),
                    ("piedmont", "Piedmont (Piemonte)"),
                    ("sardinia", "Sardinia (Sardegna)"),
                    ("sicily", "Sicily (Sicilia)"),
                    (
                        "trentino_south_tyrol",
                        "Trentino-South Tyrol (Trentino-Alto Adige)",
                    ),
                    ("tuscany", "Tuscany (Toscana)"),
                    ("umbria", "Umbria"),
                    ("veneto", "Veneto"),
                ],
                help_text="Select the region where you provide this service",
                max_length=30,
                null=True,
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_status",
            field=models.CharField(max_length=100, verbose_name="service status"),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=models.CharField(max_length=100, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="service",
            name="travel_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="travel fee",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("customer", "Customer"), ("craftsman", "Craftsman")],
                max_length=10,
                verbose_name="user type",
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("plumbing", "Plumber"),
                    ("electrical", "Electrician"),
                    ("ac_technician", "AC Technician"),
                    ("carpentry", "Carpenter"),
                    ("tiling", "Tiler"),
                    ("painting", "Painter"),
                    ("furniture_maker", "Furniture Maker"),
                    ("fumigation", "Fumigator"),
                    ("dstv_technician", "DSTV Technician"),
                    ("gas_appliance", "Gas Appliance Technician"),
                    ("pop_worker", "POP Worker"),
                    ("cleaning", "Cleaner"),
                    ("aluminium_worker", "Aluminium Worker"),
                    ("welding", "Welder"),
                    ("roofing", "Roof Technician"),
                    ("solar_power", "Solar Power Technician"),
                    ("masonry", "Mason"),
                    ("glass_partitioning", "Glass/Partitioning Worker"),
                    ("bricklayer", "Bricklayer / Plasterer"),
                    ("foreman", "Foreman"),
                    ("landscaping", "Landscaping"),
                    ("appliance_repair", "Appliance Repair"),
                    ("hvac", "HVAC Services"),
                    ("security_installation", "CCTV / Security System Technician"),
                    ("generator_technician", "Generator Technician"),
                    ("interior_design", "Interior Designer"),
                    ("flooring", "Flooring / Epoxy Work"),
                    ("metal_fabrication", "Metal Fabrication"),
                    ("waterproofing", "Waterproofing Specialist"),
                    ("pest_control", "Pest Control"),
                    ("scaffolding", "Scaffolding Worker"),
                    ("site_supervisor", "Site Supervisor"),
                    ("other", "Other"),
                ],
                max_length=50,
                null=True,
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="location",
            field=models.CharField(max_length=255, verbose_name="location"),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="phone"
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="service_needed",
            field=models.CharField(max_length=255, verbose_name="service needed"),
        ),
    ]
