# Generated by Django 4.2.28 on 2026-02-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findus", "0026_alter_boostrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="craftsmanprofile",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=260, null=True, verbose_name="slug"
            ),
        ),
    ]
